### ISSUE TITLE
[feature] 예외 처리

### ISSUE THREAD

**Issue by dpdms529** [woorifisa-service-dev-3rd/backend-1st-g4-weird-quiz#21]
## 💡 Issue
예외 처리

## 📝 task

- [ ] 로그인 예외 처리
- [ ] 회원가입 예외 처리
- [x] 퀴즈 예외 처리
